-- AlterTable
ALTER TABLE "Food" ALTER COLUMN "proteins" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fats" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "carbohydrates" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Nutrition" ALTER COLUMN "carbohydrates" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fats" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "proteins" SET DATA TYPE DOUBLE PRECISION;
